const fs = require('fs');

// File 1: New useH5Share.ts
const h5ShareContent = [
"// #ifdef H5",
"import { ensureWxReady, resetWxReady } from '../utils/wechat';",
"import { useAuthStore } from '../stores/auth';",
"",
"declare const wx: any;",
"",
"interface H5ShareOptions {",
"    title?: string;",
"    desc?: string;",
"    link?: string;",
"    imageUrl?: string;",
"}",
"",
"function buildShareLink(baseUrl: string): string {",
"    const authStore = useAuthStore();",
"    if (authStore.inviteCode) {",
"        const sep = baseUrl.includes('?') ? '&' : '?';",
"        return baseUrl + sep + 'ref=' + encodeURIComponent(authStore.inviteCode);",
"    }",
"    return baseUrl;",
"}",
"",
"export function useH5Share(options: H5ShareOptions = {}) {",
"    const defaultTitle = 'VShop - 精选好物';",
"    const defaultLink = window.location.href.split('#')[0];",
"",
"    ensureWxReady().then(() => {",
"        const shareData = {",
"            title: options.title || defaultTitle,",
"            desc: options.desc || '',",
"            link: buildShareLink(options.link || defaultLink),",
"            imgUrl: options.imageUrl || '',",
"        };",
"        try {",
"            wx.updateAppMessageShareData(shareData);",
"            wx.updateTimelineShareData(shareData);",
"        } catch (e) {",
"            console.warn('[useH5Share] wx share API failed:', e);",
"        }",
"    }).catch((e: any) => console.warn('[useH5Share] init failed:', e));",
"}",
"",
"export function useH5ProductShare(productName: string, slug: string, imageUrl?: string) {",
"    const base = window.location.origin + '/#/pkg-product/pages/detail?slug=' + slug;",
"    useH5Share({",
"        title: productName,",
"        desc: 'VShop 精选好物推荐',",
"        link: base,",
"        imageUrl,",
"    });",
"}",
"// #endif",
""
].join('\n');
fs.writeFileSync('e:/code/vshop/src/composables/useH5Share.ts', h5ShareContent, 'utf8');

// File 2: Rewrite useShare.ts with platform branching
const useShareContent = [
"interface ShareOptions {",
"    title?: string;",
"    path?: string;",
"    imageUrl?: string;",
"}",
"",
"/** WeChat share composable - call in page setup */",
"export function useShare(options: ShareOptions = {}) {",
"    // #ifdef MP-WEIXIN",
"    const { onShareAppMessage, onShareTimeline } = require('@dcloudio/uni-app');",
"    const defaultTitle = 'VShop - 精选好物';",
"    const defaultPath = '/pages/home/index';",
"    onShareAppMessage(() => ({",
"        title: options.title || defaultTitle,",
"        path: options.path || defaultPath,",
"        imageUrl: options.imageUrl || '',",
"    }));",
"    onShareTimeline(() => ({",
"        title: options.title || defaultTitle,",
"        query: '',",
"        imageUrl: options.imageUrl || '',",
"    }));",
"    // #endif",
"    // #ifdef H5",
"    const { useH5Share } = require('./useH5Share');",
"    useH5Share({",
"        title: options.title,",
"        link: options.path ? window.location.origin + '/#' + options.path : undefined,",
"        imageUrl: options.imageUrl,",
"    });",
"    // #endif",
"}",
"",
"/** Share product detail */",
"export function useProductShare(productName: string, slug: string, imageUrl?: string) {",
"    // #ifdef MP-WEIXIN",
"    useShare({",
"        title: productName,",
"        path: '/pkg-product/pages/detail?slug=' + slug,",
"        imageUrl,",
"    });",
"    // #endif",
"    // #ifdef H5",
"    const { useH5ProductShare } = require('./useH5Share');",
"    useH5ProductShare(productName, slug, imageUrl);",
"    // #endif",
"}",
""
].join('\n');
fs.writeFileSync('e:/code/vshop/src/composables/useShare.ts', useShareContent, 'utf8');

console.log('Task 5 files created OK');
